Reorganize orb.

diff --git a/orb.yml b/orb.yml
--- a/orb.yml
+++ b/orb.yml
@@ -4,15 +4,56 @@ description: >
   Repo Home: https://github.com/unmock/unmock-orb
   Website: https://www.unmock.io/
 
+orbs:
+  jq: circleci/jq@1.9.0
+
+parameters: &parameters
+  file:
+    type: string
+    description: "Path to test report"
+    default: "__unmock__/unmock-report.html"
+
+check_report: &check_report
+  name: Check report exists
+  command: |
+    REPORT_FILE=<< parameters.file >>
+
+    if [ -z ${REPORT_FILE} ];
+    then
+      echo "Empty or missing environment variable: REPORT_FILE";
+      exit 1;
+    fi;
+
+    if [ -f ${REPORT_FILE} ];  # File exists
+    then
+        echo "Found file, proceeding with: ${REPORT_FILE}"
+    else
+        echo "Report not found: ${REPORT_FILE}, exiting."
+        exit 1;
+    fi
+
 commands:
+  store:
+    description: "Stores Unmock test report as a CircleCI artifact"
+    parameters: *parameters
+    steps:
+      - run: *check_report
+      - store_artifacts:
+          path: << parameters.file >>
+      - jq/install
+      - run:
+        command: |
+          ARTIFACTS_URL=https://circleci.com/api/v1.1/project/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BUILD_NUM}/artifacts
+          echo "URL: ${ARTIFACTS_URL}"
   upload:
     description: "Uploads unmock jest-reporter results and makes a note on your PR if you have a GH integration. The orb is in early alpha stage, and its usage should be considered experimental. Note that the uploaded report will be publicly available on the internet. If your tests in CircleCI use real API keys or tokens for HTTP requests, this orb is not (yet) for you. Any and all feedback is appreciated!"
-    parameters:
-      file:
-        type: string
-        description: "Path to test report"
-        default: "__unmock__/unmock-report.html"
+    parameters: *parameters
     steps:
+      - run: *check_report
+      - run:
+          name: Print BUILD_URL
+          command: |
+            echo "Your test report lives here: ${CIRCLE_BUILD_URL}"
       - run:
           name: Upload file and post notification
           command: |
@@ -21,22 +62,6 @@ commands:
 
             # Use the error status of the first failure, rather than that of the last item in a pipeline.
             set -o pipefail
-
-            REPORT_FILE=<< parameters.file >>
-
-            if [ -z ${REPORT_FILE} ];
-            then
-              echo "Empty or missing environment variable: REPORT_FILE";
-              exit 1;
-            fi;
-
-            if [ -f ${REPORT_FILE} ];  # File exists
-            then
-                echo "Uploading file: ${REPORT_FILE}"
-            else
-                echo "Report not found: ${REPORT_FILE}, exiting."
-                exit 1;
-            fi
 
             # Post the report and save URL
             REPORT_URL=$(curl -F 'html=@"'"${REPORT_FILE}"'"' https://unmock-ci.azurewebsites.net/reports)
